### ISSUE TITLE
Support for creating and updating dashboards

### ISSUE THREAD

**Issue by antonmos** [gethop-dev/dashboard-manager.grafana#14]
Any plans to add? I may have time to contribute this but don't want to duplicate any existing efforts.

Thanks!

**Comment by dhryniewicz** [comment]
Hello Anton! Nice hearing from you.

We thought about implementing it but no real work was done in that area yet. Would be great if you'd contribute!
We do, however, need to ask contributors to sign a Contributor Agreement. We don't have the protocol for that complete yet so we'll be able to tell you more about the procedure early next week if that's ok with you.

Until then, have a great weekend!

**Comment by antonmos** [comment]
Sounds good!

**Comment by antonmos** [comment]
following up on this! Thanks

**Comment by asiergaldos** [comment]
Hi,

Sorry for the late reply.

The CLA signing procedure in place now and that it will be triggered when you create a pull request with your contribution.

Thanks!

**Comment by antonmos** [comment]
I created https://github.com/magnetcoop/dashboard-manager.grafana/pull/16 as a first step in this direction. Looking forward to your review!

**Comment by bgalartza** [comment]
Hello antonmos!
We needed this feature urgently for a customer project, so we decided to implement it ourselves. We hope you didn't start with it, and we duplicated work! We are closing the issue, but fell free to reopen it if you think something is missing or could be improved.
Best regards

**Comment by antonmos** [comment]
Glad to hear! unfortunately, my priorities changed, so i couldnt work on this! will give it a whirl!
