### ISSUE TITLE
Add minimal datasource management support

### ISSUE THREAD

**Issue by lucassousaf** [gethop-dev/dashboard-manager.grafana#9]
Things to add:
* Create a new datasource
* Update a datasource
* Delete a datasource
* Get all datasources

Reference link: https://grafana.com/docs/http_api/data_source/

**Comment by bgalartza** [comment]
Done in commit [622aba5](https://github.com/magnetcoop/dashboard-manager.grafana/commit/4622aba5919c9aed9f60e4ebd2fc609d2b88f1f6)
